#!/usr/bin/env ruby

################################################################################
# Simple MQTT Demo in Ruby
#
# REQUIRED:
#   gem install mqtt
#
# for more info see: 
#   https://github.com/njh/ruby-mqtt
#
# Author: Zvi Avraham <zvi-AT-zadata-DOT-com>
# Copyright (C) 2012 ZADATA Ltd. All Rights Reserved.
################################################################################

require 'rubygems'
require 'mqtt'

# To find your MQTT Username and Password
# login into your ZADATA account and click  navbar -> "Settings" -> "Credentials"
MQTT_USERNAME       = 'YOUR-MQTT-USER'
MQTT_PASSWORD       = 'YOUR-MQTT-PUBLISHER-PWD'
MQTT_HOST           = 'mqtt.zadata.com'
MQTT_PORT           = 1883
KEEPALIVE_IN_SECS   = 25

MQTT_SETTINGS = {
  remote_host: MQTT_HOST,
  remote_port: MQTT_PORT,
  username:    MQTT_USERNAME,
  password:    MQTT_PASSWORD,
  keep_alive:  KEEPALIVE_IN_SECS
}

# Publish example (ClientID autogenerated)
MQTT::Client.connect(MQTT_SETTINGS) do |c|
  c.publish('some/long/topic', 'Hello, World!', true) # set retain=true
end

# Subscribe example (ClientID autogenerated)
MQTT::Client.connect(MQTT_SETTINGS) do |c|
  # If you pass a block to the get method, then it will loop
  c.get('some/long/topic') do |topic,message|
    puts "#{topic}: #{message}"
  end
end
